---
# backuppc_server tasks to configure Apache2 for BackupPC access

- name: APACHE2_MODULE | Add module
  apache2_module:
    name: "{{ module }}"
    state: present
  loop:
  - rewrite
  - ssl
  loop_control:
    loop_var: module
    
- name: TEMPLATE | Copy apache config on Debian
  template:
    dest: "/etc/apache2/sites-available/{{ backuppc_srv_server_name }}.conf"
    src: etc/apache/apache.conf.j2
    owner: root
    group: root
    mode: "0644"
    backup: yes
  when: ansible_facts['distribution'] == "Debian"
  notify: BackupPC_server - restart apache2

- name: TEMPLATE | Copy apache config on Ubuntu
  template:
    dest: "/etc/backuppc/apache.conf"
    src: etc/apache/apache.conf.Ubuntu.j2
    owner: root
    group: root
    mode: "0644"
    backup: yes
  when: ansible_facts['distribution'] == "Ubuntu"
  notify: BackupPC_server - restart apache2

- name: FILE | Remove default apache2 site.
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: BackupPC_server - restart apache2
  when:
  - ansible_facts['distribution'] == "Debian" and backuppc_srv_disable_apache_default_site | bool


- name: FILE | Activate custom Backuppc apache site.
  file:
    path: "/etc/apache2/sites-enabled/{{ backuppc_srv_server_name }}.conf"
    src: "/etc/apache2/sites-available/{{ backuppc_srv_server_name }}.conf"
    state: link
  notify: BackupPC_server - restart apache2
  when: ansible_facts['distribution'] == "Debian"

- name: LINEINFILE | Require SSL to access to Apache2 BackupPC interface
  lineinfile:
    path: '{{ backuppc_srv_config_dir }}/apache.conf'
    backrefs: yes
    regexp: '^(\s*)#?SSLRequireSSL$'
    line: '\1SSLRequireSSL'
    backup: yes
    state: present
  notify: BackupPC_server - restart apache2
  when:
  - ansible_facts['distribution'] == "Debian"
  - backuppc_srv_apache_require_ssl | bool

- name: LINEINFILE | Configure distant access to Apache2 BackupPC interface
  lineinfile:
    path: '{{ backuppc_srv_config_dir }}/apache.conf'
    backrefs: yes
    regexp: '(\s*)(# |)Require (ip|local)'

    line: "\\1{{ '# ' if not backuppc_srv_apache_access_control }}Require {{ backuppc_srv_apache_Require if backuppc_srv_apache_Require is defined else 'local' }}"
    backup: yes
    state: present
  notify: BackupPC_server - restart apache2
  when:
  - ansible_facts['distribution'] == "Debian"
  - ansible_facts['distribution_major_version'] | int >= 10

...
